---
title: "meet_up_presentation"
author: "nino melitauri"
date: "October 4, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## R პროექტი

- მოსახერხებელი პრაქტიკაა, იმისათვის, რომ მოვათავსოთ ერთ პროექტთან დაკავშირებული ყველა დოკუმენტი ერთ სამუშაო ფოლდერში. 
- ასეთი დოკუმენტები შეიძლება იყოს ნებისმიერი სახის: Rstudios-ს სინტაქსი, მონაცემების ფაილი, გამომავალი გრაფიკები და ცხრილები და ა.შ.



## ახალი პროექტის შექმნა

- ახალი პროექტის შესაქმნელად შევდივართ: File – New Project
- წარმოიქმნება ახალი ფაილი "Rproj" განზომილებით, პროექტის გახსნა გადაგვიყვანს პროგრამაში და მუშაობის განმავლობაში შენახული ყველა დოკუმენტი შეინახება მოცემულ პროექტში

პროექტის უპირატესობა:
პროექტის ფაილი და სამუშაო ფაილი ერთი და იგივეა მოცემულ შემთხვევაში



## RMarkdown 
- არის ფაილის ფორმატი, რომელიც აერთიაებს R -ის ნაწილების სინტაქს და ტექსტს, რომელიც knitr -ის საშუალებით გარდაიქმნება markdown -ის, HTML, pdf და სხვა ფორმატებში .
- დაინსტალირება
install.packages("rmarkdown")
- გავხსნათ ახალი rmarkdown -ის ფაილი

## Notebook

ახალი rmarkdown -ის ფაილი გამოვა Notebook -ის ინტერფეისით
ვხედავთ, რომ ფაილი შინაარსობრივად სამი განსხვავებული ინფორმაციის მატარებელია:

>- დეფისებით --- შემოსაზღვრული არჩევითი ინფორმაცია, მოიცავს დოკუმენტის სათაურს, ავტორს და ა.შ.
>- R სინტაქსის ნაწილები (chunks), ``` -ით შემოსაზღვრული
>- ჩვეულებრივი მარტივი ფორმატით დაწერილი ტექსტი
>- ნაწილების ზედა მარჯვენა კუთხეში გაშვების ბრძანებით განვახორციელებთ ცალკეულ ოპერაციებს, შედეგები გვექნება ფაილშივე.

## R-ის ნაწილები  (chunks) 

R-ის ნაწილები შეგვიძლია გამოვიყენოთ R-ის შედეგის დოკუმენტად დაგენერირებისთვის, ან უბრალოდ კოდის მოსახერხებელი ფორმით საილუსტრაციოდ. 

R-ის ნაწილები წარმოქმნიან ასევე გრაფიკებს.


ახალი ნაწილის ჩასართავად ვიყენებთ insert + R 

ან ავკრიფოთ ხელით: ```{r} და ჩავუწეროთ ტექსტი  

ხაზთაშორისი ტექსტის ასაკრეფად r -ით დავიწყოთ კოდის აკრეფა 




## R-ის ნაწილების რამდენიმე ოპცია:

ახალი ნაწილის შექმნისას სასურველ ოპციას ვუთითებთ ფრჩხილებში
მაგალითად, ```{r eval=TRUE, echo=FALSE}

>- include = FALSE - საბოლოო ფაილში დამალავს კოდს და შედეგებს. თუმცა R Markdown გაუშვებს ამ კოდს და შედეგები გამოყენებული იქნება სხვა ნაწილებში.
>- echo = FALSE საბოლოო შედეგში დამალავს მხოლოდ კოდებს, შედეგებს გამოაჩენს. მოსახერხებელი გზაა გრაფიკების ჩასართავად.
>- message = FALSE კოდების მიერ წარმოქმნილ შეტყობინებებს დამალავს საბოლოო ფაილში.
>- warning = FALSE საბოლოო შედეგში დამალავს კოდების მიერ წარმოქმნილ გამაფრთხილებელ შეტყობინებებს.
>-მეტი ოპციებისთვის იხილეთ ლინკი:
https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf.



## დოკუმენტის დაგენერირება

პირველი ალტერნატივაა ბრძანება render

library(rmarkdown)
render(nino.Rmd)

მეორე უფრო მოსახერხებელი ალტერნატივა არის knit-ის გამოყენება, კერძოდ ჩამოვშალოთ ღილაკი, ავირჩიოთ სასურველი ფორმატი და გავუშვათ ბრძანება

პროგრამა დოკუმენტებს აგენერირებს Pandoc -ით, რომელიც არის ინსტრუმენტი Rstudio-ს ფარგლებში, დოკუმენტების კონვერტირებისთვის ერთი ფორმატიდან მეორეში


## პრეზენტაციის მომზადება

File -> New File -> presentation

დავარქვათ სახელი: "my slides"
ჩავწეროთ ავტორის სახელი და გვარი: "ნინო მელითაური"

მოვნიშნოთ ოპცია:HTML(ioslides)

## პირველი გვერდი

იწყება ერთი ძიეზით, დავწეროთ: # სათაური

ავკრიფოთ ქვედა ხაზზე: პრეზენტაციის პირველი სლაიდი

დანარჩენ სლაიდებს დავიწყებთ ორი ##-ით

თუ არ გვინდა, რომ სლაიდს ჰქონდეს სათაური ძიეზების ნაცვლად დავსვამთ სამ ვარსკვლავს***


## Bullets

შეგვიძლია სლაიდზე ტექსტი ჩამოვწეროთ ბულეტებად, დეფისის გამოყენებით.
მაგალითად, - პირველი ბულეტი - მეორე ბულეტი - მესამე ბულეტი.

თუ გვინდა, რომ ნელ-ნელა გამოვიდეს ბულეტები, სტრიქონებს შემდეგნაირად ჩამოვწერთ:
>- პირველი ბულეტი >- მეორე ბულეტი >- მესამე ბულეტი

# გმადლობთ ყურადღებისთვის

